### ISSUE TITLE
URL change

### ISSUE THREAD

**Issue by one-angry-researcher** [hoenie-ams/PyDSWS#3]
Hi, 
because of the rebranding from Thomson Reuters to Refinitiv, the API will move from https://datastream.thomsonreuters.com/ to https://product.datastream.com/. Access via the old URL is about to be deprecated. The methods get_data() and get_usage() currently still use the old URL.

**Comment by hoenie-ams** [comment]
Thanks for raising this issue and apologies for the late reply. The links have now been fixed (87c6539b594034ec3c11d243f70a54dc3ea34928) and a new release has been pushed to https://www.pypi.org
